welcome message implementation
GalacticsTeam/galactics-bot-enhanced pull request #30
Opened 2024-05-28 22:18 UTC by nour-elhabbal

Co-authored-by: Omar Lawatey <omarlawatey@gmail.com>

Message to the team leader:
hey Omar, I did the welcome message as an embed not as an image, because i tried a lot to do it as an image but i just failed as this is very complicated process. wanna hear your review about my code asap <3

2024-06-03 05:46 UTC, OmarLawaty requested changes
Over all good Job

2024-06-03 05:46 UTC, OmarLawaty commented on src/actionHandlers/welcome.ts
> +  member.roles.member;
Why did you leave this line ?

2024-06-03 05:46 UTC, OmarLawaty commented on src/actionHandlers/welcome.ts
> +export const welcome = (member: GuildMember) => {
Remember to change the function name to onWelcome

2024-06-03 05:46 UTC, OmarLawaty commented on src/actions/onGuildMemberAdd.ts
> +import { welcome } from '../actionHandlers/welcome';
Separate local imports from module imports using new line

2024-06-03 11:58 UTC, nour-elhabbal commented on src/actionHandlers/welcome.ts
> +  member.roles.member;
just forgot to remove it :<

2024-06-03 12:22 UTC, OmarLawaty commented on src/actionHandlers/welcome.ts
> +  member.roles.member;
np :)

2024-06-03 16:51 UTC, OmarLawaty requested changes

2024-06-03 16:51 UTC, OmarLawaty commented on src/actionHandlers/welcome.ts
> +    `);
Add ".then()" after the role add

2024-06-04 00:55 UTC, OmarLawaty requested changes

2024-06-04 00:55 UTC, OmarLawaty commented on package.json
> +  "type": "module",
```suggestion
  "type": "module",
```
This shouldn't be added

2024-06-04 01:11 UTC, OmarLawaty approved these changes

2024-06-04 01:11 UTC, merged